services:
  catalogue:
    build:
      dockerfile: catalogue.Dockerfile
    image: vijayalakshmi/catalogue:1.0.0
    container_name: catalogue
    depends_on:
    - mongodb
  mongodb:
    build: 
      dockerfile: mongodb.Dockerfile # it moves to mongodb directory
    image: vijayalakshmitv/mongodb:1.0.0 #docker build -t vijayalakshmitv/mongodb:1.0.0 
    container_name: mongodb
    
  networks:
    default:
    driver: bridge
    name: roboshop
    external: false # if true, you need to create network manually
