services:
  catalogue:
    build: ./catalogue
    image: vijayalakshmitv/catalogue:1.0.0
    container_name: catalogue
    depends_on:
      - mongodb
  user:
    build: ./user
    image: vijayalakshmitv/user:1.0.0
    container_name: user
    depends_on:
    - redis
  cart:
    build: ./cart
    image: vijayalakshmitv/cart:1.0.0
    container_name: cart
    depends_on:
    - redis
  frontend:
    build: ./frontend
    image: vijayalakshmitv/frontend:1.0.0
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
  mongodb:
    build: ./mongodb
    image: vijayalakshmitv/mongodb:1.0.0
    container_name: mongodb
  redis:
    image: redis:7.0
    container_name: redis
  mysql:
    build: ./mysql
    image: vijayalakshmitv/mysql:1.0.0
    container_name: mysql    

networks:
  roboshop:
    driver: bridge
    name: roboshop
